name: xcodebuild
description: Configures and runs xcodebuild
inputs:
  codesign:
    description: 'Enable code-signing'
    required: false
    default: 'NO'
  device:
    description: 'Test Simulator'
    required: false
    default: 'iPhone 16'
  scheme:
    description: 'xcodebuild scheme'
    required: false
    default: 'Solutions'
runs:
  using: "composite"
  steps:
    - name: Setup Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      shell: bash
    - name: Compute Options
      id: options
      run: echo "options=-scheme ${{ inputs.scheme }}
        -destination 'platform=iOS Simulator,name=${{ inputs.device }}'
        -jobs 2
        CODE_SIGNING_ALLOWED=${{ inputs.codesign }} | xcbeautify --renderer github-actions" >> $GITHUB_OUTPUT
      shell: bash
    - name: Restore SPM Cache
      uses: actions/cache@v5
      with:
        path: ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
        key: ${{ runner.os }}-${{ runner.arch }}-spm-${{ hashFiles('**/*.xc*') }}
        restore-keys: ${{ runner.os }}-${{ runner.arch }}-spm-
outputs:
  options:
    description: "Build Options"
    value: ${{ steps.options.outputs.options }}
