name: xcodebuild
description: Configures and runs xcodebuild
inputs:
  codesign:
    description: 'Enable code-signing'
    required: false
    default: 'NO'
  destination:
    description: 'xcodebuild destination'
    required: false
    default: 'platform=iOS Simulator,OS=26.0.1,name=iPhone 16'
  scheme:
    description: 'xcodebuild scheme'
    required: false
    default: 'Solutions'
  task:
    description: 'xcodebuild action'
    required: false
    default: 'build'
runs:
  using: "composite"
  steps:
    - name: Setup Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      shell: bash
    - name: Restore Build Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          ~/Library/Caches/org.swift.swiftpm
          !~/Library/Developer/Xcode/DerivedData/**/Logs/**
        key: ${{ runner.os }}-xcodebuild-${{ env.XCODE_VERSION }}-${{ hashFiles('**/*.xc*') }}
        restore-keys: |
          ${{ runner.os }}-xcodebuild-${{ env.XCODE_VERSION }}
    - name: Run xcodebuild
      run: |
        env NSUnbufferedIO=YES xcodebuild ${{ inputs.task }} \
        -scheme ${{ inputs.scheme }} \
        -destination "${{ inputs.destination }}" \
        -showBuildTimingSummary \
        CODE_SIGNING_ALLOWED=${{ inputs.codesign }} \
        2>&1 | xcbeautify --renderer github-actions
      shell: bash

