name: xcodebuild
description: Configures and runs xcodebuild
inputs:
  codesign:
    description: 'Enable code-signing'
    required: false
    default: 'NO'
  scheme:
    description: 'xcodebuild scheme'
    required: false
    default: 'Solutions'
runs:
  using: "composite"
  steps:
    - name: Setup Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      shell: bash
    - name: Compute Destination
      id: destination
      run: |
        target=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed 's/Simulator//g' | awk '{$1=$1;print}'`
        echo "destination='platform=iOS Simulator,name=$target'" >> $GITHUB_OUTPUT
      shell: bash
    - name: Compute Options
      id: options
      run: echo "options=-scheme ${{ inputs.scheme }} -destination ${{ steps.destination.outputs.destination }} -jobs 2 -showBuildTimingSummary CODE_SIGNING_ALLOWED=${{ inputs.codesign }} | xcbeautify --renderer github-actions" >> $GITHUB_OUTPUT
      shell: bash
outputs:
  destination:
    description: "Computed Destination"
    value: ${{ steps.destination.outputs.destination }}
  options:
    description: "Build Options"
    value: ${{ steps.options.outputs.options }}
