name: xcodebuild
description: Configures and runs xcodebuild
inputs:
  codesign:
    description: 'Enable code-signing'
    required: false
    default: 'NO'
  command:
    description: 'xcodebuild command'
    required: false
    default: 'build'
  codeql:
    description: 'CodeQL build'
    required: false
    default: ${{ contains(github.workflow, 'codeql') && 'YES' || 'NO' }}
  scheme:
    description: 'xcodebuild scheme'
    required: false
    default: 'Solutions'
  version:
    description: 'xcode version'
    required: false
    default: '26.1'
runs:
  using: "composite"
  steps:
    - name: Setup Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ inputs.version }}.app
      shell: bash
    - name: Compute Destination
      id: destination
      run: |
        target=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed 's/Simulator//g' | awk '{$1=$1;print}'`
        echo "destination='platform=iOS Simulator,name=$target'" >> $GITHUB_OUTPUT
      shell: bash
    - name: Compute command
      id: command
      run: echo command="env NSUnbufferedIO=YES SWIFTPM_MAX_CONCURRENT_OPERATIONS=2
        xcodebuild ${{ inputs.command }}
        -scheme ${{ inputs.scheme }}
        -destination ${{ steps.destination.outputs.destination }}
        -jobs 2
        -disablePackageRepositoryCache
        ${{ inputs.codeql == 'YES' && '-skipPackageUpdates -skipPackageSignatureValidation -skipPackagePluginValidation -skipMacroValidation COMPILATION_CACHE_ENABLE_CACHING=NO' || '' }}
        CODE_SIGNING_ALLOWED=${{ inputs.codesign }} | xcbeautify --renderer github-actions" >> $GITHUB_OUTPUT
      shell: bash
    - name: Build Cache
      uses: actions/cache@v5
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          !~/Library/Developer/Xcode/DerivedData/**/Logs/**
        key: xcodebuild-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.xc*', '**/*.swift') }}
        restore-keys: xcodebuild-${{ runner.os }}-${{ runner.arch }}-
    - name: Clean
      if: inputs.codeql == 'YES'
      run: env NSUnbufferedIO=YES xcodebuild clean -scheme ${{ inputs.scheme }} | xcbeautify --renderer github-actions
      shell: bash
outputs:
  command:
    description: "Build Command"
    value: ${{ steps.command.outputs.command }}
