name: xcodebuild
description: Configures and runs xcodebuild
inputs:
  codesign:
    description: 'Enable code-signing'
    required: false
    default: 'NO'
  scheme:
    description: 'xcodebuild scheme'
    required: false
    default: 'Solutions'
  version:
    description: 'xcode version'
    required: false
    default: '26.1'
runs:
  using: "composite"
  steps:
    - name: Setup Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ inputs.version }}.app
      shell: bash
    - name: Compute Destination
      id: destination
      run: |
        target=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed 's/Simulator//g' | awk '{$1=$1;print}'`
        echo "destination='platform=iOS Simulator,name=$target'" >> $GITHUB_OUTPUT
      shell: bash
    - name: Compute Options
      id: options
      run: echo "options=-scheme ${{ inputs.scheme }}
        -destination ${{ steps.destination.outputs.destination }}
        -jobs 2
        CODE_SIGNING_ALLOWED=${{ inputs.codesign }}
        NSUnbufferedIO=YES
        SWIFTPM_MAX_CONCURRENT_OPERATIONS=2 | xcbeautify --renderer github-actions" >> $GITHUB_OUTPUT
      shell: bash
    - name: Restore SPM Cache
      uses: actions/cache@v5
      with:
        path: ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
        key: ${{ runner.os }}-${{ runner.arch }}-spm-${{ hashFiles('**/*.xc*') }}
        restore-keys: ${{ runner.os }}-${{ runner.arch }}-spm-
outputs:
  options:
    description: "Build Options"
    value: ${{ steps.options.outputs.options }}
