name: xcodebuild
description: Configures and runs xcodebuild
inputs:
  codesign:
    description: 'Enable code-signing'
    required: false
    default: 'NO'
  scheme:
    description: 'xcodebuild scheme'
    required: false
    default: 'Solutions'
  version:
    description: 'xcode version'
    required: false
    default: '26.1'
runs:
  using: "composite"
  steps:
    - name: Setup Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ inputs.version }}.app
      shell: bash
    - name: Compute Destination
      id: destination
      run: |
        target=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed 's/Simulator//g' | awk '{$1=$1;print}'`
        echo "destination='platform=iOS Simulator,name=$target'" >> $GITHUB_OUTPUT
      shell: bash
    - name: Compute command
      id: options
      run: echo options="-scheme ${{ inputs.scheme }}
        -destination ${{ steps.destination.outputs.destination }}
        -jobs ${{ contains(runner.arch, 'ARM') && 2 || 3 }}
        CODE_SIGNING_ALLOWED=${{ inputs.codesign }} | xcbeautify --renderer github-actions" >> $GITHUB_OUTPUT
      shell: bash
    - name: Build Cache
      id: build-cache
      uses: actions/cache/restore@v5
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          !~/Library/Developer/Xcode/DerivedData/**/Logs/**
          !**/*.xcbuilddata
        key: xcodebuild-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.xc*', '**/*.swift') }}
        restore-keys: xcodebuild-${{ runner.os }}-${{ runner.arch }}-
    - name: Resolve Package Dependencies
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: xcodebuild -resolvePackageDependencies ${{ steps.options.outputs.options }}
      shell: bash
outputs:
  build-cache-hit:
    description: "Build Cache Hit"
    value: ${{ steps.build-cache.outputs.cache-hit }}
  build-cache-key:
    description: "Build Cache Key"
    value: ${{ steps.build-cache.outputs.cache-primary-key }}
  options:
    description: "Build options"
    value: ${{ steps.options.outputs.options }}
