name: xcodebuild
description: Configures and runs xcodebuild
inputs:
  codesign:
    description: 'Enable code-signing'
    required: false
    default: 'NO'
  scheme:
    description: 'xcodebuild scheme'
    required: false
    default: 'Solutions'
runs:
  using: "composite"
  steps:
    - name: Setup Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app
      shell: bash
    - name: Set Build Command Variables
      id: command
      run: |
        echo target=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed 's/Simulator//g' | awk '{$1=$1;print}'` >> $GITHUB_OUTPUT
        echo destination="platform=iOS Simulator,name=$target"
        echo options="-scheme ${{ inputs.scheme }} -destination $destination -jobs 2 -showBuildTimingSummary CODE_SIGNING_ALLOWED=${{ inputs.codesign }} | xcbeautify --renderer github-actions"
      shell: bash
outputs:
  destination:
    description: "Computed Destination"
    value: ${{ steps.command.outputs.destination }}
  options:
    description: "Build Options"
    value: ${{ steps.command.outputs.options }}
