// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GAMDirect",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "GAMDirect",
            targets: ["AppModule"],
            bundleIdentifier: "adsbynimbus.solutions.GAMDirect",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .flower),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/adsbynimbus/nimbus-ios-sdk", "2.32.0"..<"3.0.0"),
        .package(url: "https://github.com/googleads/swift-package-manager-google-mobile-ads", "12.14.0"..<"13.0.0"),
        .package(path: "../../../sdk-extensions/ios/aps-swiftpm")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "NimbusKit", package: "nimbus-ios-sdk"),
                .product(name: "APS-SwiftPM", package: "aps-swiftpm"),
                .product(name: "GoogleMobileAds", package: "swift-package-manager-google-mobile-ads")
            ],
            path: ".",
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
