name: gradle
description: Configures and runs a Gradle task
inputs:
  cache-encryption-key:
    description: 'Setup Gradle cache-encyrption-key'
    required: true
  cache-read-only:
    description: 'Setup Gradle cache-read-only'
    required: false
    default: ${{ github.ref != 'refs/heads/main' }}
  dependency-graph:
    description: 'Setup Gradle dependency-graph'
    required: false
    default: 'disabled'
  jdk-vendor:
    description: 'Setup Java distribution'
    required: false
    default: 'zulu'
  jdk-version:
    description: 'Setup Java java-version'
    required: false
    default: '25'
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: ${{ inputs.jdk-vendor }}
        java-version: ${{ inputs.jdk-version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-encryption-key: ${{ inputs.cache-encryption-key }}
        cache-read-only: ${{ inputs.cache-read-only }}
        dependency-graph: ${{ inputs.dependency-graph }}
    - name: Determine Kotlin Version
      id: kotlin
      run: echo VERSION=`grep "^kotlin =" gradle/libs.versions.toml | sed 's/[^"]*"\([^"]*\).*/\1/'` >> $GITHUB_OUTPUT
      shell: bash
    - name: Clean Kotlin Native Directory
      run: rm -rf ~/.konan
      shell: bash
    - name: Restore Kotlin Native
      uses: actions/cache/restore@v5
      id: kotlin-cache
      with:
        path: ~/.konan
        key: ${{ runner.os }}-${{ runner.arch }}-konan-${{ steps.kotlin.outputs.VERSION }}
outputs:
  kotlin-cache-key:
    description: "Kotlin Cache Key"
    value: ${{ steps.kotlin-cache.outputs.cache-primary-key }}
