name: Next Gen SDK

on:
  push:
    tags:
      - 'nextgen/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Publish Next Gen SDK
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '24'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          dependency-graph: generate-and-submit
      - name: Set Version from Tag Name
        id: tag_name
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/nextgen/}" >> $GITHUB_OUTPUT
      - name: Publish
        if: github.repository == 'adsbynimbus/solutions'
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.tag_name.outputs.VERSION }}
        run: ./gradlew :dynamicprice:nextgen:sdk:publish
